name: Daily Stock Fetch

on:
  schedule:
    - cron: "30 7 * * 1-5" # 每週一到五，台灣時間下午3:30（UTC時間07:30）

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests pandas

    - name: Run main.py
      run: |
        python main.py

    - name: Commit and push data
      run: |
        git config user.name "GitHub Actions"
        git config user.email "dog4891072@gmail.com"
        git add data/
        git commit -m "Daily update: $(date '+%Y-%m-%d')" || echo "No changes"
        git push
