# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:  # 僅手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas lxml html5lib beautifulsoup4

      - name: Run main.py
        run: |
          python ./Test.py

      - name: Commit and push data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "dog4891072@gmail.com"
          git add data/
          git commit -m "Manual update: $(date '+%Y-%m-%d')" || echo "No changes"
          git push